# Neural Network and Classification
- É utilizado para determinar qual grupo os dados pertencem
- Na aplicação da rede neural para classificação, a camada de saída é geralmente formulado de forma diferente dependendo de quantos grupos os dados devem ser divididos.

# Binary Classification
- São classificados em 2 grupos
- Para esse sistema, um único nó de saida é suficiente
- O número de nós de entrada é o mesmo que número de parâmetros
- O código para esse programa é basicamente o código de Back-Propagation do capítulo 3.

# Multiclass Classification
- Utilizado para classificar 3 ou mais classes considerando as entradas (x,y)
- Considerando uma rede contendo 3 classes, teremos 3 nós de saída, gerando assim um vetor para as classes
- Para classificação, é utilizado a função softmax 
- A função softmax mantém a soma dos valores de saída em 1 e também limita as saídas individuais dentro dos valores de 0-1

# Example: Multiclass Classification
- Classificação de imagem 5x5, onde teremos 25 nós de entrada, será utilizado a função softmax para ativação no nó de saída, enquanto nas camadas ocultas será utilizado a função sigmoid 
- É utilizado o método one-hot para classificar as saídas

In [12]:
import numpy as np

#Implementaçao da função softmax
def Softmax(x):
    x  = np.subtract(x, np.max(x))
    ex = np.exp(x)
    
    return ex / np.sum(ex)

def TestMultiClass():
    
    #Inicializa a matriz com zeros
    X = np.zeros((5, 5, 5))
    
    #Inicializa a matriz com o número 1
    X[:, :, 0] = [[0,1,1,0,0],
                  [0,0,1,0,0],
                  [0,0,1,0,0],
                  [0,0,1,0,0],
                  [0,1,1,1,0]]
    
    #Inicializa a matriz com o número 2
    X[:, :, 1] = [[1,1,1,1,0],
                  [0,0,0,0,1],
                  [0,1,1,1,0],
                  [1,0,0,0,0],
                  [1,1,1,1,1]]
    
    #Inicializa a matriz com o número 3
    X[:, :, 2] = [[1,1,1,1,0],
                  [0,0,0,0,1],
                  [0,1,1,1,0],
                  [0,0,0,0,1],
                  [1,1,1,1,0]]
    
    #Inicializa a matriz com o número 4
    X[:, :, 3] = [[0,0,0,1,0],
                  [0,0,1,1,0],
                  [0,1,0,1,0],
                  [1,1,1,1,1],
                  [0,0,0,1,0]]
    
    #Inicializa a matriz com o número 5
    X[:, :, 4] = [[1,1,1,1,1],
                  [1,0,0,0,0],
                  [1,1,1,1,0],
                  [0,0,0,0,1],
                  [1,1,1,1,0]]
    
    #Matriz de rsultados espeados
    D = np.array([[[1,0,0,0,0]],
                  [[0,1,0,0,0]],
                  [[0,0,1,0,0]],
                  [[0,0,0,1,0]],
                  [[0,0,0,0,1]]])
    
    # Inicializa um valor aleatório para os pesos
    W1 = 2*np.random.random((50, 25)) - 1
    W2 = 2*np.random.random(( 5, 50)) - 1
    
    #Inicia o aprendizado
    for _epoch in range(10000):
        alpha = 0.9
    
        N = 5
        #Percorre as matrizes de teste
        for k in range(N):
            x = np.reshape(X[:,:,k], (25, 1)) #Transforma a matiz em um vetor 25x1
            d = D[k, :].T #Tanspoem a matriz de resultados

            #Primeiro neurônio
            v1 = np.matmul(W1, x) #Multiplica W1 (peso) com o array de teste
            y1 = 1.0 / (1.0 + np.exp(-v1)) #Calcula a saída do neurônio (função de ativação sigmoid)
            
            #Segundo neurônio
            v  = np.matmul(W2, y1) #Multiplica W2 (peso) com o array gerado pelo primeiro neurônio
            y  = Softmax(v) #Calcula a saída do neurônio (função de ativação softmax)

            #Segundo neurônio
            e = d - y #Calcula o erro
            delta = e #Calculado o delta em cima do erro

            #Primeiro neurônio
            e1 = np.matmul(W2.T, delta) #Calcula o erro
            delta1 = y1*(1-y1) * e1 #Calculado o delta em cima do erro

            #Primeiro neurônio
            dW1 = alpha * delta1 * x.T #Calcula a correção do peso
            W1  = W1 + dW1 #Acumula a correção corrigindo o peso

            #Segundo neurônio
            dW2 = alpha * delta * y1.T #Acumula a correção corrigindo o peso
            W2  = W2 + dW2 #Acumula a correção corrigindo o peso
    
        
    N = 5
    for k in range(N):
        x  = np.reshape(X[:, :, k], (25, 1)) #Transforma a matriz em um vetor 25x1
        v1 = np.matmul(W1, x) #Multiplica a matriz W1 (pesos) com a matriz de entrada
        y1 = 1.0 / (1.0 + np.exp(-v1)) #Calcula a saída do neurônio pela função sigmoid
        v  = np.matmul(W2, y1) #Multiplica a matriz W (pesos) com o resultado do neurônio anterior
        y  = Softmax(v) #Cálcula a saída do neurônio pela função softmax
        
        print("Y = {}: ".format(k+1))
        print(y) #Exibe os resultados.
    
    return W1, W2

if __name__ == '__main__':
    TestMultiClass()

Y = 1: 
[[9.99990706e-01]
 [1.95306793e-06]
 [3.01828146e-06]
 [4.16796621e-06]
 [1.54304377e-07]]
Y = 2: 
[[1.49616556e-06]
 [9.99984633e-01]
 [1.05984136e-05]
 [2.97874340e-06]
 [2.93809503e-07]]
Y = 3: 
[[3.40994834e-06]
 [9.77046320e-06]
 [9.99971391e-01]
 [9.59025004e-07]
 [1.44694891e-05]]
Y = 4: 
[[4.30715086e-06]
 [3.22326255e-06]
 [1.98359513e-08]
 [9.99990362e-01]
 [2.08726881e-06]]
Y = 5: 
[[3.96366364e-06]
 [2.18004800e-06]
 [1.09424189e-05]
 [2.50223032e-06]
 [9.99980412e-01]]


## Real Multiclass

In [14]:
import numpy as np

#Implementaçao da função softmax
def Softmax(x):
    x  = np.subtract(x, np.max(x))
    ex = np.exp(x)
    
    return ex / np.sum(ex)

def TestMultiClass():
    
    #Inicializa a matriz com zeros
    X = np.zeros((5, 5, 5))
    
    #Inicializa a matriz com o número 1
    X[:, :, 0] = [[0,1,1,0,0],
                  [0,0,1,0,0],
                  [0,0,1,0,0],
                  [0,0,1,0,0],
                  [0,1,1,1,0]]
    
    #Inicializa a matriz com o número 2
    X[:, :, 1] = [[1,1,1,1,0],
                  [0,0,0,0,1],
                  [0,1,1,1,0],
                  [1,0,0,0,0],
                  [1,1,1,1,1]]
    
    #Inicializa a matriz com o número 3
    X[:, :, 2] = [[1,1,1,1,0],
                  [0,0,0,0,1],
                  [0,1,1,1,0],
                  [0,0,0,0,1],
                  [1,1,1,1,0]]
    
    #Inicializa a matriz com o número 4
    X[:, :, 3] = [[0,0,0,1,0],
                  [0,0,1,1,0],
                  [0,1,0,1,0],
                  [1,1,1,1,1],
                  [0,0,0,1,0]]
    
    #Inicializa a matriz com o número 5
    X[:, :, 4] = [[1,1,1,1,1],
                  [1,0,0,0,0],
                  [1,1,1,1,0],
                  [0,0,0,0,1],
                  [1,1,1,1,0]]
    
    #Matriz de rsultados espeados
    D = np.array([[[1,0,0,0,0]],
                  [[0,1,0,0,0]],
                  [[0,0,1,0,0]],
                  [[0,0,0,1,0]],
                  [[0,0,0,0,1]]])
    
    # Inicializa um valor aleatório para os pesos
    W1 = 2*np.random.random((50, 25)) - 1
    W2 = 2*np.random.random(( 5, 50)) - 1
    
    #Inicia o aprendizado
    for _epoch in range(10000):
        alpha = 0.9
    
        N = 5
        #Percorre as matrizes de teste
        for k in range(N):
            x = np.reshape(X[:,:,k], (25, 1)) #Transforma a matiz em um vetor 25x1
            d = D[k, :].T #Tanspoem a matriz de resultados

            #Primeiro neurônio
            v1 = np.matmul(W1, x) #Multiplica W1 (peso) com o array de teste
            y1 = 1.0 / (1.0 + np.exp(-v1)) #Calcula a saída do neurônio (função de ativação sigmoid)
            
            #Segundo neurônio
            v  = np.matmul(W2, y1) #Multiplica W2 (peso) com o array gerado pelo primeiro neurônio
            y  = Softmax(v) #Calcula a saída do neurônio (função de ativação softmax)

            #Segundo neurônio
            e = d - y #Calcula o erro
            delta = e #Calculado o delta em cima do erro

            #Primeiro neurônio
            e1 = np.matmul(W2.T, delta) #Calcula o erro
            delta1 = y1*(1-y1) * e1 #Calculado o delta em cima do erro

            #Primeiro neurônio
            dW1 = alpha * delta1 * x.T #Calcula a correção do peso
            W1  = W1 + dW1 #Acumula a correção corrigindo o peso

            #Segundo neurônio
            dW2 = alpha * delta * y1.T #Acumula a correção corrigindo o peso
            W2  = W2 + dW2 #Acumula a correção corrigindo o peso
    
        
    N = 5
    for k in range(N):
        x  = np.reshape(X[:, :, k], (25, 1)) #Transforma a matriz em um vetor 25x1
        v1 = np.matmul(W1, x) #Multiplica a matriz W1 (pesos) com a matriz de entrada
        y1 = 1.0 / (1.0 + np.exp(-v1)) #Calcula a saída do neurônio pela função sigmoid
        v  = np.matmul(W2, y1) #Multiplica a matriz W (pesos) com o resultado do neurônio anterior
        y  = Softmax(v) #Cálcula a saída do neurônio pela função softmax
    
    return W1, W2

def RealMultiClass():   
    W1, W2 = TestMultiClass() #Recebe os pesos do treinamento
    
    #Inicializa a matriz com zeros
    X = np.zeros((5, 5, 5))
    
    #Matriz contaminada
    X[:, :, 0] = [[0,0,1,1,0],
                  [0,0,1,1,0],
                  [0,1,0,1,0],
                  [0,0,0,1,0],
                  [0,1,1,1,0]]
    
    #Matriz contaminada
    X[:, :, 1] = [[1,1,1,1,0],
                  [0,0,0,0,1],
                  [0,1,1,1,0],
                  [1,0,0,0,1],
                  [1,1,1,1,1]]
    
    #Matriz contaminada
    X[:, :, 2] = [[1,1,1,1,0],
                  [0,0,0,0,1],
                  [0,1,1,1,0],
                  [1,0,0,0,1],
                  [1,1,1,1,0]]
    
    #Matriz contaminada
    X[:, :, 3] = [[0,1,1,1,0],
                  [0,1,0,0,0],
                  [0,1,1,1,0],
                  [0,0,0,1,0],
                  [0,1,1,1,0]]
    
    #Matriz contaminada
    X[:, :, 4] = [[0,1,1,1,1],
                  [0,1,0,0,0],
                  [0,1,1,1,0],
                  [0,0,0,1,0],
                  [1,1,1,1,0]]
      
        
    N = 5
    for k in range(N):
        x  = np.reshape(X[:, :, k], (25, 1)) #Transforma a matriz em um vetor 25x1
        v1 = np.matmul(W1, x) #Multiplica a matriz W1 (pesos) com a matriz de entrada
        y1 = 1.0 / (1.0 + np.exp(-v1)) #Calcula a saída do neurônio pela função sigmoid
        v  = np.matmul(W2, y1) #Multiplica a matriz W (pesos) com o resultado do neurônio anterior
        y  = Softmax(v) #Cálcula a saída do neurônio pela função softmax
        
        print("N = {}: ".format(k+1))
        print(y) #Exibe os resultados.

if __name__ == '__main__':
    RealMultiClass()

N = 1: 
[[1.90651023e-01]
 [2.07885186e-02]
 [1.19104368e-04]
 [6.78003794e-01]
 [1.10437560e-01]]
N = 2: 
[[7.55415882e-05]
 [9.60430309e-01]
 [3.89193611e-02]
 [3.49967023e-04]
 [2.24820918e-04]]
N = 3: 
[[5.43983530e-05]
 [3.17410209e-03]
 [9.96556526e-01]
 [9.96591774e-05]
 [1.15313891e-04]]
N = 4: 
[[0.2398421 ]
 [0.11387758]
 [0.22318721]
 [0.06303932]
 [0.36005379]]
N = 5: 
[[0.01089815]
 [0.01079417]
 [0.00291109]
 [0.00273637]
 [0.97266022]]


- Para a primeira imagem a rede decidiu que era 4, por mais que pareça 1 temos mais características do número 4
- Para a segunda imagem a rede decidiu que era 2, de forma compatível por só ter 1 pixel fora do lugar 
- A terceira imagem é classificada como 3, que também é razoável para sua classificação
- Comparando a segunda e a terceira imagem, a diferençã é de apenas um pixel, que gerou uma total diferença na classificação.
- A quarta imagem é classificada como 5, porém com apenas 47% de probabilidade ao mesmo tempo, também poderia ser o 3, com 32%. Para esses casos, a rede deve ser treinada para poder melhorar sua performace.
- A quinta imagem é classificada como 5 com 98%, de forma razoável, porém a imagem é muito semelhante a quarta. Podemos notar que a diferença é de apenas um pixel que levou a classificação a ser dessa forma.